# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZhuJessica_Final' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZhuJessica_Final
	
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

  target 'ZhuJessica_FinalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZhuJessica_FinalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
